# ./.github/workflows/build-deploy.yml

name: deploy

on:
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
  push:
    branches: master

jobs:
  use-build:
    # adapt to point to the current repo
    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#calling-a-reusable-workflow
    # change this to the current repo
    uses: joel07p/stealthchat/.github/workflows/build.yml@master
    # that's all - jobs that call a reusable workflow can do nothing else 1

  deploy:
    # only run the 'deploy' job if the 'use-build' job passes
    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idneeds
    needs: use-build

    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
#      - name: Download backend artifact
#        # https://github.com/actions/download-artifact
#        uses: actions/download-artifact@v4.1.2
#        with:
#          # the same name as used in the build workflow
#          name: build-artifact-backend
#          # where to save the artifact
#         # using the same path as in the build workflow "restores" the state from the end of the build workflow
#          path: backend/dist      
        
    # deploy! adapt to your needs.
      - name: Upload backend via RSYNC
        # https://github.com/marketplace/actions/ftp-action
        # 'with' config is specific to the 'sebastianpopp/ftp-action' action
        uses: actions/checkout@v4.1.1
      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: backend/dist/
          remote_path: ${{ secrets.BACKEND_DIR }}/dist
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          
#      - name: Download frontend artifact
#        # https://github.com/actions/download-artifact
#        uses: actions/download-artifact@v4.1.2
#        with:
#          # the same name as used in the build workflow
#          name: build-artifact-frontend
#          # where to save the artifact
#          # using the same path as in the build workflow "restores" the state from the end of the build workflow
#          path: frontend/dist
      - name: Upload frontend via RSYNC
        # https://github.com/marketplace/actions/ftp-action
        # 'with' config is specific to the 'sebastianpopp/ftp-action' action
        uses: actions/checkout@v4.1.1
      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: frontend/dist/
          remote_path: ${{ secrets.FRONTEND_DIR }}/dist
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          
      - uses: appleboy/ssh-action@master
        name: connect to server and restart webservices | pm2 | nginx
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            service nginx stop
            cd ${{ secrets.BACKEND_DIR }}
            pm2 kill
            rm -rf node_modules
            npm i
            pm2 start --name backend/nest dist/main.js
            cd ${{ secrets.FRONTEND_DIR }}
            pm2 start --name frontend/react npm -- run preview
